# #######################################################
# Copyright 2021 - 2022 Ma Yaning
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #######################################################
#/
##
# @file docker-compose.yml
# @Brief  Consul测试环境
# @author Ma Yaning, <mayaning4coding@163.com>
# @version 0.1
# @date 2022-03-16
#/

version: "3"
services:
  DC1Server1:
    image: consul:latest
    container_name: "DC1Server1"
    volumes:
      - $CFGDIR/DC1Server1.json:/etc/consul.d/DC1Server1.json
    command: 
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul
  DC1Server2:
    image: consul:latest
    container_name: "DC1Server2"
    volumes:
      - $CFGDIR/DC1Server2.json:/etc/consul.d/DC1Server2.json
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul
  DC1Server3:
    image: consul:latest
    container_name: "DC1Server3"
    volumes:
      - $CFGDIR/DC1Server3.json:/etc/consul.d/DC1Server3.json
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul
  DC1Client1:
    image: consul:latest
    container_name: "DC1Client1"
    volumes:
      - $CFGDIR/DC1Client1.json:/etc/consul.d/DC1Client1.json
      - $CFGDIR/ServiceTest.sh:/usr/bin/ServiceTest.sh
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul
  DC1Client2:
    image: consul:latest
    container_name: "DC1Client2"
    volumes:
      - $CFGDIR/DC1Client2.json:/etc/consul.d/DC1Client2.json
      - $CFGDIR/ServiceTest.sh:/usr/bin/ServiceTest.sh
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul

  DC2Server1:
    image: consul:latest
    container_name: "DC2Server1"
    volumes:
      - $CFGDIR/DC2Server1.json:/etc/consul.d/DC2Server1.json
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul
  DC2Server2:
    image: consul:latest
    container_name: "DC2Server2"
    volumes:
      - $CFGDIR/DC2Server2.json:/etc/consul.d/DC2Server2.json
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul
  DC2Server3:
    image: consul:latest
    container_name: "DC2Server3"
    volumes:
      - $CFGDIR/DC2Server3.json:/etc/consul.d/DC2Server3.json
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul
  DC2Client1:
    image: consul:latest
    container_name: "DC2Client1"
    volumes:
      - $CFGDIR/DC2Client1.json:/etc/consul.d/DC2Client1.json
      - $CFGDIR/ServiceTest.sh:/usr/bin/ServiceTest.sh
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul
  DC2Client2:
    image: consul:latest
    container_name: "DC2Client2"
    volumes:
      - $CFGDIR/DC2Client2.json:/etc/consul.d/DC2Client2.json
      - $CFGDIR/ServiceTest.sh:/usr/bin/ServiceTest.sh
    command:
      /usr/bin/consul agent -config-dir /etc/consul.d
    networks:
      - consul

  AppClient:
    image: consul:latest
    container_name: "AppClient"
    networks:
      - consul

networks:
  consul:
